add_executable(UnitTests main.cpp parameters/testParameters.cpp parameters/parameterUtils.cpp)
if(GITHUB_VM)
    target_compile_definitions(UnitTests PRIVATE GITHUB_VM)
endif()
target_link_libraries(UnitTests PRIVATE PowerFlowLib)
add_test(NAME UnitTests COMMAND UnitTests WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
