/*
 * GENERATED BY CMAKE
 */
/*
 * Public header including definitions of primitive types used in SCS.
 * Make sure this file and `scs.h` are somewhere appropriate and then use
 * `#include "scs.h"` to access the SCS public API.
 */
#ifndef SCS_TYPES_H_GUARD
#define SCS_TYPES_H_GUARD

#ifdef __cplusplus
extern "C" {
#endif

typedef long long   scs_int;
typedef double scs_float;
typedef double scs_complex_float[2]; /* [real, imaginary] */

#ifdef __cplusplus
}
#endif
#endif
